projectName     = STORM
githubURL       = https://github.com/apache/storm.git
localPath       = repo-storm
root            = /home/federico/IdeaProjects/progettoISW2/repo-storm/

# Modalità: BUILD (generazione Dataset) o LABEL (esecuzione Labeling), FULL (entrambi), FEATURE_SELECTIONS
executionMode   = FEATURE_SELECTIONS
datasetPath     = output/STORM_Metrics_Dataset.csv
versionsPath    = output/STORM_Version_Table.csv
finalDataset    = output/STORM_Final_Metrics_Dataset.csv