projectName     = STORM
githubURL       = https://github.com/apache/storm.git
localPath       = repo-storm
root            = /home/federico/IdeaProjects/progettoISW2/repo-storm/

# Modalità: BUILD (crea metriche) o LABEL (applica bug) o FULL (entrambi)
executionMode   = LABEL
datasetPath     = output/STORM_Metrics_Dataset.csv