package it.uniroma2.ISW2.Pepe.Federico;

public record ItemCsv(int numRelease,
                      String versionName,
                      String commitId,
                      String classPath,
                      int wmc,
                      int cbo,
                      int dit,
                      int rfc,
                      int lcom,
                      int loc,
                      int nOfMethod,
                      int nOfField,
                      long npm,
                      float dam,
                      int moa,
                      float mfa,
                      float cam,
                      float amc,
                      int nRevisions,
                      int loaAdded,
                      int locDeleted,
                      float maxChurm,
                      float avgChurm,
                      int nSmells,
                      boolean buggy) {}
